<a href="https://colab.research.google.com/github/y-fares/PSTB_DI_Bootcamp/blob/main/Week2/Day1/ExerciseXP/Gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Python script to check if a given number is a prime number. For example, check if the number 7 is prime.

In [1]:
def is_prime(num):
    if num <= 1:
        print(num, "is not a prime number")
        return False

    flag = False
    for i in range(2, num):
        if num % i == 0:
            flag = True
            break

    if flag:
        print(num, "is not a prime number")
    else:
        print(num, "is a prime number")

In [3]:
is_prime(9)

9 is not a prime number

Exercise 2: List Comprehensions with Jupyter Notebook.
Instructions
Launch Jupyter Notebook on your local machine.
Create a new notebook.
Write a Python script using list comprehensions to find all numbers in a given range (e.g., 1 to 20) that are divisible by a specific number (e.g., 3).

In [4]:
def find_divisible_numbers(start, end, divisor):
    divisible_numbers = [num for num in range(start, end + 1) if num % divisor == 0]
    return divisible_numbers

In [5]:
debut = 1
fin = 20
diviseur = 3
find_divisible_numbers(debut, fin, diviseur)

[3, 6, 9, 12, 15, 18]

Exercise 3: Kaggle Dataset Exploration: Print Dataset Information
Instructions
Choose a dataset other than Titanic from Kaggle (e.g., Iris Dataset).
Write a script to print the head, columns, and data types of the chosen dataset (either on Google Colab or Jupyter notebook)

In [2]:
import pandas as pd

In [4]:
!wget https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Iris%20Dataset.zip

--2025-10-09 12:32:00--  https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Iris%20Dataset.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Iris%20Dataset.zip [following]
--2025-10-09 12:32:01--  https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D2%20-%20Data%20U.%20and%20pre-processing/Iris%20Dataset.zip
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1293 (1.3K) [application/zip]
Saving to: ‘Iris Dataset.zip’

Iris Dataset.zip    100%[===================>]   1.26K  --.-KB/s    in 0s

2025-10-09 12:32:01 (51.2 MB/s) - ‘Iris Dataset.zip’ saved [1293/1293]

In [5]:
!unzip Iris\ Dataset.zip

Archive:  Iris Dataset.zip
  inflating: Iris Dataset/Iris.csv

In [6]:
data_iris = pd.read_csv('Iris Dataset/Iris.csv')

In [7]:
data_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
data_iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
data_iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

Exercise 4: Basic Data Analysis with Kaggle
Instructions
Select a simple dataset from Kaggle (e.g., Boston Housing Dataset).
Perform basic data analysis to find the mean, median, and standard deviation of a particular column.

In [10]:
data_iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
data_iris["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

Exercise 5: Transforming Qualitative Data into Quantitative Data with the Titanic Dataset
Instructions
Download the Titanic dataset from a source like Kaggle.
Load the dataset into a Python environment using Pandas.
Transform the sex column, to represent 0 as ‘female’ and 1 for ‘male’ using .map function.

In [14]:
!mkdir -p ~/.kaggle

In [16]:
!cp kaggle.json ~/.kaggle/

In [17]:
!chmod 600 ~/.kaggle/kaggle.json

In [18]:
!kaggle competitions download -c titanic

Downloading titanic.zip to /content
  0% 0.00/34.1k [00:00<?, ?B/s]
100% 34.1k/34.1k [00:00<00:00, 129MB/s]

In [19]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [30]:
pd_titanic = pd.read_csv("test.csv")

In [31]:
pd_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [32]:
pd_titanic['Sex'] = pd_titanic['Sex'].map({'female': 0, 'male': 1})

In [33]:
pd_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,S